import { NextRequest, NextResponse } from 'next/server'
import { CreateChildSchema } from '@/lib/auth/validation'
import { hashPassword } from '@/lib/auth/passwords'
import { generateUniqueUsername, AVATAR_EMOJIS } from '@/lib/auth/usernames'
import { demoStore } from '@/lib/auth/demo-store'
import crypto from 'crypto'

function resolveParentFromRequest(req: NextRequest): string | null {
  const sessionToken = req.cookies.get('lu_parent_session')?.value
  if (!sessionToken) return null

  const sessionHash = crypto.createHash('sha256').update(sessionToken).digest('hex')
  const session = demoStore.sessionByHash(sessionHash)

  if (!session || session.userType !== 'parent' || session.revokedAt) return null
  if (new Date(session.expiresAt) <= new Date()) return null

  return session.userId
}

export async function POST(req: NextRequest) {
  const parentId = resolveParentFromRequest(req)
  if (!parentId) {
    return NextResponse.json({ error: 'Parent session required.' }, { status: 401 })
  }

  const body = await req.json().catch(() => null)
  const parsed = CreateChildSchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Validation error" }, { status: 400 })
  }

  const { firstName, avatarAnimal, age, grade, password } = parsed.data

  // If username was pre-generated by the UI, accept it — otherwise generate fresh
  const providedUsername = (body as Record<string, unknown>)?.username as string | undefined
  let username: string

  if (providedUsername && !demoStore.usernameExists(providedUsername)) {
    username = providedUsername
  } else {
    username = await generateUniqueUsername(
      avatarAnimal,
      firstName,
      async (u) => demoStore.usernameExists(u)
    )
  }

  const passwordHash = await hashPassword(password)

  const child = {
    id:           crypto.randomUUID(),
    parentId,
    firstName,
    displayName:  firstName,
    username,
    passwordHash,
    avatarAnimal,
    age,
    grade,
    currentXp:    0,
    currentLevel: 1,
  }

  demoStore.children.set(child.id, child)

  return NextResponse.json({
    success: true,
    child: {
      id:          child.id,
      firstName:   child.firstName,
      username:    child.username,
      avatarAnimal: child.avatarAnimal,
      avatarEmoji: AVATAR_EMOJIS[child.avatarAnimal],
      grade:       child.grade,
    },
  })
}
