/**
 * Level Up seed data
 * Run: npx ts-node -r tsconfig-paths/register db/seed.ts
 * Or use the Supabase dashboard to run the generated SQL.
 */

export const SEED_INTERESTS = [
  { name: 'Space', category: 'Science & Technology', emoji: '🚀' },
  { name: 'Dinosaurs', category: 'Nature & Animals', emoji: '🦕' },
  { name: 'Minecraft', category: 'Gaming', emoji: '⛏️' },
  { name: 'Karate', category: 'Sports & Fitness', emoji: '🥋' },
  { name: 'Soccer', category: 'Sports & Fitness', emoji: '⚽' },
  { name: 'Animals', category: 'Nature & Animals', emoji: '🐾' },
  { name: 'Cooking', category: 'Life Skills', emoji: '🍳' },
  { name: 'Gaming', category: 'Gaming', emoji: '🎮' },
  { name: 'Technology', category: 'Science & Technology', emoji: '💻' },
  { name: 'Music', category: 'Arts & Culture', emoji: '🎵' },
]

export const SEED_BADGES = [
  {
    name: 'First Step',
    description: 'Complete your first lesson',
    emoji: '👣',
    criteria_json: { lessons_completed: 1 },
  },
  {
    name: 'Curious Mind',
    description: 'Complete 5 Curiosity lessons',
    emoji: '🔭',
    criteria_json: { curiosity_lessons: 5 },
  },
  {
    name: 'Scholar',
    description: 'Complete 5 School Mode lessons',
    emoji: '🎓',
    criteria_json: { school_lessons: 5 },
  },
  {
    name: 'Mission Possible',
    description: 'Complete your first Mission',
    emoji: '🎯',
    criteria_json: { missions_completed: 1 },
  },
  {
    name: 'Chain Breaker',
    description: 'Complete a full learning chain',
    emoji: '⛓️',
    criteria_json: { chains_completed: 1 },
  },
  {
    name: 'Level 5',
    description: 'Reach Level 5',
    emoji: '⭐',
    criteria_json: { level: 5 },
  },
  {
    name: 'Space Explorer',
    description: 'Complete 3 Space-themed lessons',
    emoji: '🚀',
    criteria_json: { interest_lessons: { Space: 3 } },
  },
  {
    name: 'Science Star',
    description: 'Master a Science concept',
    emoji: '🔬',
    criteria_json: { mastered_subjects: ['Science'] },
  },
]

export const SEED_CURIOSITY_LESSONS = [
  {
    title: 'The Physics Behind a Karate Kick',
    mode: 'curiosity',
    category: 'Sports Science',
    subject: 'Science',
    grade_min: 4,
    grade_max: 8,
    difficulty: 2,
    hook: 'Why does a karate kick break boards? Science explains everything!',
    script: 'When a karate master kicks, they are applying focused force to a small area.\nThe faster the kick, the more kinetic energy is transferred.\nForce equals mass times acceleration — that is Newton\'s Second Law in action.\nConcentrating force on a single point creates enough pressure to split wood!',
    summary: 'Discover how Newton\'s Laws of Motion explain the science of martial arts.',
    estimated_duration_seconds: 45,
    interest_tags: ['karate', 'sports', 'science'],
    thumbnail_emoji: '🥋',
    fallback_animation_json: {
      scenes: [
        { id: 's1', type: 'title', text: 'Why does a karate kick break boards?', emoji: '🥋', bg_color: '#e74c3c', text_color: '#ffffff', duration_ms: 3000, transition: 'fade' },
        { id: 's2', type: 'fact', text: 'Force = Mass × Acceleration', emoji: '💪', bg_color: '#c0392b', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's3', type: 'fact', text: 'Focused force on a small area = massive pressure!', bg_color: '#922b21', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's4', type: 'celebration', text: 'You just learned Newton\'s 2nd Law! 🔥', emoji: '⭐', bg_color: '#f39c12', text_color: '#ffffff', duration_ms: 2500, transition: 'zoom' },
      ],
    },
  },
  {
    title: 'Why Do Rockets Have Multiple Stages?',
    mode: 'curiosity',
    category: 'Space Science',
    subject: 'Science',
    grade_min: 4,
    grade_max: 9,
    difficulty: 2,
    hook: 'Rockets drop parts of themselves on the way to space — here\'s why that\'s genius!',
    script: 'Getting to space requires escaping Earth\'s gravity — that takes enormous fuel.\nCarrying empty fuel tanks slows you down, just like carrying a heavy backpack.\nBy dropping empty stages, the rocket gets lighter and faster as it climbs.\nThis staged approach is the only way we can reach orbit with today\'s technology!',
    summary: 'Learn how staged rockets use physics to escape Earth\'s gravity.',
    estimated_duration_seconds: 50,
    interest_tags: ['space', 'technology', 'science'],
    thumbnail_emoji: '🚀',
    fallback_animation_json: {
      scenes: [
        { id: 's1', type: 'title', text: 'Why do rockets drop pieces of themselves?', emoji: '🚀', bg_color: '#1a1a2e', text_color: '#ffffff', duration_ms: 3000, transition: 'fade' },
        { id: 's2', type: 'fact', text: 'Empty tanks are dead weight in space!', bg_color: '#16213e', text_color: '#a8d8ea', duration_ms: 4000, transition: 'slide' },
        { id: 's3', type: 'fact', text: 'Drop the stage → get lighter → go faster 🚀', bg_color: '#0f3460', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's4', type: 'celebration', text: 'You understand rocket staging! 🌟', emoji: '⭐', bg_color: '#f39c12', text_color: '#ffffff', duration_ms: 2500, transition: 'zoom' },
      ],
    },
  },
  {
    title: 'How Minecraft Teaches You Real Math',
    mode: 'curiosity',
    category: 'Gaming & Math',
    subject: 'Math',
    grade_min: 3,
    grade_max: 7,
    difficulty: 1,
    hook: 'Every time you build in Minecraft, you\'re doing real math!',
    script: 'Building a house in Minecraft means calculating area and volume.\nA 10×10 floor uses 100 blocks — that\'s area: length times width.\nFilling it 5 blocks high? That\'s volume: length × width × height = 500 blocks!\nMinecraft players are constantly doing geometry without even realizing it.',
    summary: 'Discover how the world\'s most popular game is secretly teaching you mathematics.',
    estimated_duration_seconds: 40,
    interest_tags: ['minecraft', 'gaming', 'math'],
    thumbnail_emoji: '⛏️',
    fallback_animation_json: {
      scenes: [
        { id: 's1', type: 'title', text: 'Minecraft is secretly teaching you math!', emoji: '⛏️', bg_color: '#2ecc71', text_color: '#ffffff', duration_ms: 3000, transition: 'fade' },
        { id: 's2', type: 'fact', text: 'Area = Length × Width (your floor plan!)', bg_color: '#27ae60', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's3', type: 'fact', text: 'Volume = L × W × H (fill that building!)', bg_color: '#1e8449', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's4', type: 'celebration', text: 'Math master builder! 🏗️', emoji: '⭐', bg_color: '#f39c12', text_color: '#ffffff', duration_ms: 2500, transition: 'zoom' },
      ],
    },
  },
  {
    title: 'The Secret Language of Animals',
    mode: 'curiosity',
    category: 'Animal Science',
    subject: 'Science',
    grade_min: 2,
    grade_max: 6,
    difficulty: 1,
    hook: 'Animals talk to each other all the time — but not with words!',
    script: 'Animals communicate using sounds, colours, movements, and even smells.\nBees do a "waggle dance" to tell other bees exactly where to find flowers.\nDolphins have individual whistles like names — they call each other by sound.\nCommunication is essential for survival in every animal species on Earth.',
    summary: 'Explore the fascinating ways animals communicate without human language.',
    estimated_duration_seconds: 45,
    interest_tags: ['animals', 'science', 'nature'],
    thumbnail_emoji: '🐾',
    fallback_animation_json: {
      scenes: [
        { id: 's1', type: 'title', text: 'Animals have their own secret language!', emoji: '🐾', bg_color: '#8e44ad', text_color: '#ffffff', duration_ms: 3000, transition: 'fade' },
        { id: 's2', type: 'fact', text: 'Bees dance to give directions to flowers 🐝', bg_color: '#7d3c98', text_color: '#ffeaa7', duration_ms: 4000, transition: 'slide' },
        { id: 's3', type: 'fact', text: 'Dolphins have personal name-whistles! 🐬', bg_color: '#6c3483', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's4', type: 'celebration', text: 'Animal expert unlocked! 🦁', emoji: '⭐', bg_color: '#f39c12', text_color: '#ffffff', duration_ms: 2500, transition: 'zoom' },
      ],
    },
  },
  {
    title: 'Why Your Favourite Song Gets Stuck in Your Head',
    mode: 'curiosity',
    category: 'Brain Science',
    subject: 'Science',
    grade_min: 3,
    grade_max: 8,
    difficulty: 2,
    hook: 'Earworms are real — and neuroscience explains why music hijacks your brain!',
    script: 'An earworm is when a song replays in your mind over and over.\nYour brain loves patterns, and music is full of them — especially repetitive hooks.\nWhen a melody is unfinished or unexpected, your brain tries to complete it.\nThis is called the Zeigarnik Effect — your brain hates unfinished business!',
    summary: 'Learn about the neuroscience of memory, patterns, and why music sticks in your brain.',
    estimated_duration_seconds: 50,
    interest_tags: ['music', 'science', 'brain'],
    thumbnail_emoji: '🎵',
    fallback_animation_json: {
      scenes: [
        { id: 's1', type: 'title', text: 'Why do songs get stuck in your head?', emoji: '🎵', bg_color: '#2980b9', text_color: '#ffffff', duration_ms: 3000, transition: 'fade' },
        { id: 's2', type: 'fact', text: 'Your brain loves patterns — music is pure pattern!', bg_color: '#2471a3', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's3', type: 'fact', text: 'Zeigarnik Effect: your brain hates unfinished things 🧠', bg_color: '#1a5276', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's4', type: 'celebration', text: 'Brain science unlocked! 🧠✨', emoji: '⭐', bg_color: '#f39c12', text_color: '#ffffff', duration_ms: 2500, transition: 'zoom' },
      ],
    },
  },
]

export const SEED_SCHOOL_LESSONS = [
  {
    title: 'Forces and Motion — Newton\'s Second Law',
    mode: 'school',
    category: 'Physics',
    subject: 'Science',
    grade_min: 5,
    grade_max: 7,
    difficulty: 3,
    hook: 'Want to know why your karate kick creates power? It\'s all about force and acceleration!',
    script: 'A force is a push or pull that can change an object\'s motion.\nNewton\'s Second Law states: Force = Mass × Acceleration (F=ma).\nA heavier object needs more force to accelerate at the same rate.\nThis is why a karate kick or soccer shot transfers energy so powerfully!\nPractice: if a 2kg object accelerates at 5 m/s², the force is 10 Newtons.',
    summary: 'Master Newton\'s Second Law and understand how force, mass, and acceleration relate.',
    estimated_duration_seconds: 120,
    interest_tags: ['karate', 'sports', 'science', 'physics'],
    thumbnail_emoji: '⚡',
    fallback_animation_json: {
      scenes: [
        { id: 's1', type: 'title', text: 'F = ma: Newton\'s Second Law', emoji: '⚡', bg_color: '#e74c3c', text_color: '#ffffff', duration_ms: 3000, transition: 'fade' },
        { id: 's2', type: 'fact', text: 'Force = Mass × Acceleration', bg_color: '#c0392b', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's3', type: 'fact', text: 'More mass = more force needed to accelerate', bg_color: '#922b21', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's4', type: 'question', text: 'If mass = 2kg and acceleration = 5 m/s², what is the force?', bg_color: '#7b241c', text_color: '#ffffff', duration_ms: 5000, transition: 'fade' },
        { id: 's5', type: 'answer', text: 'Force = 2 × 5 = 10 Newtons! ✅', bg_color: '#27ae60', text_color: '#ffffff', duration_ms: 3000, transition: 'zoom' },
        { id: 's6', type: 'celebration', text: 'You\'ve mastered Newton\'s 2nd Law! 🔥', emoji: '⭐', bg_color: '#f39c12', text_color: '#ffffff', duration_ms: 2500, transition: 'zoom' },
      ],
    },
  },
  {
    title: 'Equivalent Fractions — Soccer Edition',
    mode: 'school',
    category: 'Number Sense',
    subject: 'Math',
    grade_min: 4,
    grade_max: 6,
    difficulty: 2,
    hook: 'A soccer team plays half the match — but is 1/2 the same as 2/4? Spoiler: YES!',
    script: 'Equivalent fractions are fractions that represent the same amount.\n1/2 and 2/4 are equivalent — multiply the top and bottom by the same number.\nImagine a soccer match: 45 minutes of 90 total is 1/2. That\'s also 45/90 = 1/2.\nTo create equivalent fractions, multiply or divide both numerator and denominator by the same value.\nAlways simplify fractions to their lowest terms for the clearest answer.',
    summary: 'Learn equivalent fractions using sports as a real-world context.',
    estimated_duration_seconds: 90,
    interest_tags: ['soccer', 'sports', 'math'],
    thumbnail_emoji: '⚽',
    fallback_animation_json: {
      scenes: [
        { id: 's1', type: 'title', text: 'Equivalent Fractions ⚽', emoji: '⚽', bg_color: '#2ecc71', text_color: '#ffffff', duration_ms: 3000, transition: 'fade' },
        { id: 's2', type: 'fact', text: '1/2 = 2/4 = 3/6 — they\'re all the same!', bg_color: '#27ae60', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's3', type: 'fact', text: 'Multiply top AND bottom by the same number', bg_color: '#1e8449', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's4', type: 'question', text: 'Is 3/4 equivalent to 6/8?', bg_color: '#196f3d', text_color: '#ffffff', duration_ms: 4000, transition: 'fade' },
        { id: 's5', type: 'answer', text: 'YES! 3×2=6 and 4×2=8 ✅', bg_color: '#27ae60', text_color: '#ffffff', duration_ms: 3000, transition: 'zoom' },
        { id: 's6', type: 'celebration', text: 'Fraction champion! 🏆', emoji: '⭐', bg_color: '#f39c12', text_color: '#ffffff', duration_ms: 2500, transition: 'zoom' },
      ],
    },
  },
  {
    title: 'Flight and Forces — How Planes Stay Up',
    mode: 'school',
    category: 'Forces and Flight',
    subject: 'Science',
    grade_min: 4,
    grade_max: 6,
    difficulty: 2,
    hook: 'Four forces keep planes in the air — and you can test them with a paper airplane!',
    script: 'Four forces act on every aircraft: lift, drag, thrust, and gravity.\nLift is created when air moves faster over the curved top of a wing.\nGravity pulls the plane down — lift must exceed gravity to stay airborne.\nThrust from engines pushes forward; drag from air resistance slows things down.\nBalance these four forces and you can fly anything — from paper planes to rockets.',
    summary: 'Explore the four forces of flight and how they keep aircraft airborne.',
    estimated_duration_seconds: 100,
    interest_tags: ['space', 'technology', 'science'],
    thumbnail_emoji: '✈️',
    fallback_animation_json: {
      scenes: [
        { id: 's1', type: 'title', text: 'The 4 Forces of Flight ✈️', emoji: '✈️', bg_color: '#3498db', text_color: '#ffffff', duration_ms: 3000, transition: 'fade' },
        { id: 's2', type: 'fact', text: 'LIFT ↑ vs GRAVITY ↓ — Lift must win!', bg_color: '#2980b9', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's3', type: 'fact', text: 'THRUST → vs DRAG ← — Engines push, air resists', bg_color: '#2471a3', text_color: '#ffffff', duration_ms: 4000, transition: 'slide' },
        { id: 's4', type: 'celebration', text: 'You understand flight! Time to build a paper plane! 🚀', emoji: '⭐', bg_color: '#f39c12', text_color: '#ffffff', duration_ms: 2500, transition: 'zoom' },
      ],
    },
  },
]

export const SEED_MISSIONS = [
  {
    title: 'Force in the Wild',
    description: 'Find 3 examples of force in your home or backyard. Take a photo or describe each one. How does force change how each object moves?',
    category: 'Science',
    proof_type: 'self_report',
    xp_reward: 150,
    emoji: '💪',
  },
  {
    title: 'Paper Airplane Engineer',
    description: 'Build a paper airplane and fly it 5 times. Adjust the wings and observe how it changes. Which design flew farthest? Tell someone why you think it worked best.',
    category: 'Science',
    proof_type: 'parent_confirmed',
    xp_reward: 200,
    emoji: '✈️',
  },
  {
    title: 'Kitchen Fraction Chef',
    description: 'Help make a recipe at home and identify all the fractions used. Can you find two equivalent fractions in the recipe? Show a parent or family member what you found.',
    category: 'Math',
    proof_type: 'parent_confirmed',
    xp_reward: 175,
    emoji: '🍳',
  },
  {
    title: 'Animal Communicator',
    description: 'Watch a pet, bird, or animal video for 5 minutes. Write down or tell someone 3 ways the animal communicates without words. What do you think each signal means?',
    category: 'Science',
    proof_type: 'self_report',
    xp_reward: 125,
    emoji: '🐾',
  },
  {
    title: 'Rocket Engineer',
    description: 'Build a simple straw rocket or paper cone rocket. Test it three times. Does a heavier or lighter rocket fly farther? Form a hypothesis and test it!',
    category: 'Science',
    proof_type: 'parent_confirmed',
    xp_reward: 250,
    emoji: '🚀',
  },
  {
    title: 'Minecraft Math Build',
    description: 'Build a structure in Minecraft and calculate its volume. Tell someone: how many blocks did it take? Show your area and volume math.',
    category: 'Math',
    proof_type: 'self_report',
    xp_reward: 150,
    emoji: '⛏️',
  },
  {
    title: 'Teach It Back',
    description: 'Explain one thing you learned today to a parent, sibling, or friend. Can they understand it? Teaching is the best way to know if YOU really get it!',
    category: 'Any',
    proof_type: 'parent_confirmed',
    xp_reward: 100,
    emoji: '🗣️',
  },
  {
    title: 'Nature Force Hunt',
    description: 'Go outside and find examples of gravity, friction, or air resistance in nature. Take photos or draw them. Can you name the force acting in each case?',
    category: 'Science',
    proof_type: 'photo_upload',
    xp_reward: 175,
    emoji: '🌿',
  },
  {
    title: 'Spending Tracker',
    description: 'Track everything you or your family spends money on for one day. Add it up. Which category cost the most? Create a simple fraction to show it.',
    category: 'Math',
    proof_type: 'self_report',
    xp_reward: 150,
    emoji: '💰',
  },
  {
    title: 'Fitness Physics Challenge',
    description: 'Do 10 jumping jacks, 10 push-ups, and run for 1 minute. For each exercise, identify which Newton\'s Law is at work. Explain it to someone!',
    category: 'Science & PE',
    proof_type: 'parent_confirmed',
    xp_reward: 200,
    emoji: '🏃',
  },
]

export const SEED_ONTARIO_CURRICULUM = {
  region: {
    country: 'Canada',
    province_or_state: 'Ontario',
    name: 'Ontario Curriculum',
    source_url: 'https://www.ontario.ca/page/ontario-curriculum',
    version: '2023',
    effective_date: '2023-09-01',
  },
  subjects: [
    { name: 'Math', education_level: 'elementary' },
    { name: 'Science', education_level: 'elementary' },
    { name: 'Language', education_level: 'elementary' },
    { name: 'Math', education_level: 'secondary' },
    { name: 'Science', education_level: 'secondary' },
    { name: 'English', education_level: 'secondary' },
    { name: 'Biology', education_level: 'secondary' },
  ],
  grades: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  sample_courses: [
    { subject: 'Math', grade: 1, name: 'Grade 1 Mathematics' },
    { subject: 'Language', grade: 3, name: 'Grade 3 Language Arts' },
    { subject: 'Science', grade: 5, name: 'Grade 5 Science and Technology' },
    { subject: 'Math', grade: 6, name: 'Grade 6 Mathematics' },
    { subject: 'Science', grade: 8, name: 'Grade 8 Science and Technology' },
    { subject: 'Math', grade: 9, name: 'Principles of Mathematics (MPM1D)' },
    { subject: 'Science', grade: 10, name: 'Science (SNC2D)' },
    { subject: 'Biology', grade: 11, name: 'Biology (SBI3U)' },
    { subject: 'English', grade: 12, name: 'English (ENG4U)' },
  ],
  sample_expectations: [
    {
      course: 'Grade 1 Mathematics',
      strand: 'Number',
      code: 'B1.1',
      text: 'Read, represent, compose, and decompose whole numbers up to and including 50.',
      concepts: [
        { name: 'Number Representation', description: 'Representing numbers in multiple ways' },
        { name: 'Number Decomposition', description: 'Breaking numbers into parts' },
      ],
    },
    {
      course: 'Grade 3 Language Arts',
      strand: 'Reading',
      code: 'B1.2',
      text: 'Use knowledge of words and cueing systems to read and understand texts.',
      concepts: [
        { name: 'Reading Comprehension', description: 'Understanding written text' },
        { name: 'Context Clues', description: 'Using surrounding text to determine meaning' },
      ],
    },
    {
      course: 'Grade 5 Science and Technology',
      strand: 'Forces and Motion',
      code: 'E1.1',
      text: 'Identify and describe forces, including gravity, friction, and magnetism, that act on objects.',
      concepts: [
        { name: 'Gravity', description: 'The force pulling objects toward Earth' },
        { name: 'Friction', description: 'Resistance force between surfaces' },
        { name: 'Magnetism', description: 'Magnetic forces between objects' },
      ],
    },
    {
      course: 'Grade 6 Mathematics',
      strand: 'Number',
      code: 'B1.5',
      text: 'Generate and identify equivalent fractions, including fractions greater than 1.',
      concepts: [
        { name: 'Equivalent Fractions', description: 'Fractions representing the same value' },
        { name: 'Simplifying Fractions', description: 'Reducing fractions to lowest terms' },
      ],
    },
    {
      course: 'Grade 8 Science and Technology',
      strand: 'Systems in Action',
      code: 'E1.1',
      text: 'Identify and describe the relationship between work, force, and distance.',
      concepts: [
        { name: 'Work', description: 'Force applied over a distance' },
        { name: 'Mechanical Advantage', description: 'Using machines to increase force' },
      ],
    },
  ],
}

export const SEED_LEARNING_CHAINS = [
  {
    title: 'The Science of Power',
    interest_tags: ['karate', 'sports', 'science'],
    grade_min: 5,
    grade_max: 7,
    reward_value: 300,
  },
  {
    title: 'Space: Forces and Flight',
    interest_tags: ['space', 'technology', 'science'],
    grade_min: 4,
    grade_max: 6,
    reward_value: 350,
  },
  {
    title: 'Math in the Game',
    interest_tags: ['minecraft', 'gaming', 'math'],
    grade_min: 3,
    grade_max: 7,
    reward_value: 250,
  },
]
